### PR TITLE
Correct deserialize of ObjectSpaceObjectPropSet

### PR DESCRIPTION
**Pull request by blu-base**
According to [MS-ONESTORE], section 2.6.1, the optional field ContextIDs is
only present if OSIDs is present and the OSIDs.header.ExtendedStreamsPresent
field is true.

This commit nests the check whether there is a ContextIDs field present
into the branch where the optional field OSIDs is present.
If OSIDs is not present, ContextIDs cannot be present as well according
to the specification.

Please see the issue #45 for discussion.

### CODE REVIEW

**Comment by tomjebo** [comment]
@blu-base the code looks correct but need to check OneNote code per my comments in #45 before we can merge this.

**Comment by tomjebo** [comment]
@blu-base Update on this, I ran the tests with this change and three of them failed. Without it they pass. I'll need to do a little more investigation and will follow up later.

**Comment by blu-base** [comment]
Hi Tom, thank you for your insight! This narrows down which assumption was right.
I'll close this PR then.

**Comment by tomjebo** [comment]
@blu-base actually, can you reopen this? Sorry for the confusion. See my edited comment.

**Comment by tomjebo** [comment]
@blu-base  I reopened it for you. I still need to run the S01 tests. Even if the code is functionally equivalent to the original, I would probably support using yours as it is per the specification. We just need to determine if the specification is correct or needs a behavior note.

**Comment by tomjebo** [comment]
@blu-base all the tests pass. We are looking at the specification to make sure it's accurately reflecting the OneNote behavior or if there's a deviation in OneNote. I'll let you know once we confirm.

**Comment by blu-base** [comment]
Thanks for the update!

**Comment by tomjebo** [comment]
@blu-base we've confirmed that OneNote behavior actually covers use of the bit in both OIDs and OSIDs and since the MS-ONESTORE spec references OSIDs.header.ExtendedStreamsPresent in this context, it's best to use your change. I'll merge this today. Thank you again for taking the time to help improve our test suites!

**Comment by tomjebo** [comment]
@blu-base we've confirmed that OneNote behavior actually covers use of the bit in both OIDs and OSIDs and since the MS-ONESTORE spec references OSIDs.header.ExtendedStreamsPresent in this context, it's best to use your change. I'll merge this today. Thank you again for taking the time to help improve our test suites!

**Pull request merged**
